services:
  pmp-tracker:
    build: ./pmp-tracker
    ports:
      - "38429:8080"
  pmp-client:
    build: ./pmp-client
    ports:
     - 4173:4173
    environment:
      - TRACKER_URL=http://pmp-tracker:8080/pmp-tracker/rest
  dev-service-1:
    build: .
    depends_on:
      - pmp-tracker
    ports:
      - "64017:64017"
    environment:
      - SERVICE_INFO_PMPROOT=http://localhost:64017
      - SERVICE_INFO_ENVIRONMENT=development
      - SERVICE_INFO_NAME=dev-service-1
      - TRACKER_URL=http://pmp-tracker:8080
  dev-service-2:
    build: .
    depends_on:
      - pmp-tracker
    ports:
      - "64018:64017"
    environment:
      - SERVICE_INFO_PMPROOT=http://localhost:64018
      - SERVICE_INFO_ENVIRONMENT=development
      - SERVICE_INFO_NAME=dev-service-2
      - TRACKER_URL=http://pmp-tracker:8080
  dev-service-3:
    build: .
    depends_on:
      - pmp-tracker
    ports:
      - "64019:64017"
    environment:
      - SERVICE_INFO_PMPROOT=http://localhost:64019
      - SERVICE_INFO_ENVIRONMENT=development
      - SERVICE_INFO_NAME=dev-service-3
      - TRACKER_URL=http://pmp-tracker:8080
  preprod-service-1:
    build: .
    depends_on:
      - pmp-tracker
    ports:
      - "64020:64017"
    environment:
      - SERVICE_INFO_PMPROOT=http://localhost:64020
      - SERVICE_INFO_ENVIRONMENT=preprod
      - SERVICE_INFO_NAME=preprod-service-1
      - TRACKER_URL=http://pmp-tracker:8080
  preprod-service-2:
    build: .
    depends_on:
      - pmp-tracker
    ports:
      - "64021:64017"
    environment:
      - SERVICE_INFO_PMPROOT=http://localhost:64021
      - SERVICE_INFO_ENVIRONMENT=preprod
      - SERVICE_INFO_NAME=preprod-service-2
      - TRACKER_URL=http://pmp-tracker:8080
  preprod-service-3:
    build: .
    depends_on:
      - pmp-tracker
    ports:
      - "64022:64017"
    environment:
      - SERVICE_INFO_PMPROOT=http://localhost:64022
      - SERVICE_INFO_ENVIRONMENT=preprod
      - SERVICE_INFO_NAME=preprod-service-3
      - TRACKER_URL=http://pmp-tracker:8080
