name: Client Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: pmp-client
        run: |
          npm ci
          npx playwright install --with-deps
      # - uses: stepek/tsc-action@master
      - name: Typescript typecheck
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
      - name: Unit / Integration tests
        working-directory: pmp-client
        run: npm run test
      - name: Playwright tests
        working-directory: pmp-client
        run: npm run test:e2e

        # TODO: upload unit / integration test report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: pmp-client/playwright-report/
          retention-days: 30
